additional ITemplateResolver leads to problem
2022-01-04 18:52:43.027 ERROR 290633 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "templates/examples/restrictedAccessThymeleafExampleSVG.svg")] with root cause

org.thymeleaf.exceptions.TemplateProcessingException: Instantiation of new objects and access to static classes is forbidden in this context (template: "/examples/restrictedAccessThymeleafExampleSVG" - line 23, col 11)